FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar deps de Python
COPY ./app/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY ./app .

# El backend escuchará en 4322 dentro del contenedor
ENV FLASK_ENV=development
ENV PORT=4322
EXPOSE 4322