FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar deps de Python (sin apt)
COPY ./app/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY ./app .

EXPOSE 8000
ENV FLASK_ENV=development

# Ajusta si tu entrypoint es distinto
CMD ["python", "app.py"]